### ISSUE TITLE
The ad can not be shown when app is not in foreground (Android-iOS interstitial ad show issue)

### ISSUE THREAD

**Issue by aykutuludag** [googleads/googleads-mobile-flutter#1196]
**Flutter version:** 3.24.3
**Dart version:** 3.5.3
**Affected Android versions:** Happening in every Android versions:
**Affected iOS versions:** Happening in every iOS versions.

**The issue**
This issue is still present google_mobile_ads: ^5.2.0. To be clear, I suspect that **this error happening all kind of fullscreen ads** (Open Ads, Interstitial Ads etc). **Not happening in every time** according to firebase data, it is happening around %10 of intertititial show calls. So only **%90** of interstitial can be showed successfully.

Error Reasons:
For Android >>> **The ad can not be shown when app is not in foreground.**
For iOS >>> **the provided view controller is not being presented.**
For Both >>> **The consent form has already been shown.**

For Android:

**Sceneario**
As general the other apps, I am showing interstitial ads between screen changes. Here is my code:

```
InterstitialAd? fullPageAd;

Future<void> initializeAdmob() async {
    await MobileAds.instance.initialize();
    await createInterstitialAd();
}

Future<void> createInterstitialAd() async {
  if (adCount < 2) {
    var adCompleter = Completer<void>();

    // If ads can't load within 2.5 seconds, skip
    Timer(Duration(milliseconds: 2500), () {
      if (!adCompleter.isCompleted) {
        adCompleter.complete();
      }
    });

    await InterstitialAd.load(
        adUnitId: Platform.isAndroid ? interstitialAndroid : interstitialiOS,
        request: request,
        adLoadCallback: InterstitialAdLoadCallback(
          onAdLoaded: (InterstitialAd ad) {
            if (!adCompleter.isCompleted) {
              adCompleter.complete();
            }
            fullPageAd = ad;
            fullPageAd!.setImmersiveMode(true);
            FirebaseAnalytics.instance.logEvent(
              name: "interstitialLOAD",
            );
          },
          onAdFailedToLoad: (LoadAdError error) async {
            FirebaseAnalytics.instance.logEvent(
              name: "interstitialFAILLOAD",
              parameters: {
                "errorReason": error.message,
              },
            );
          },
        ));

    await adCompleter.future;
  }
}
```

```
Future<void> showInterstitialAd(
    BuildContext context, void Function() changeScreen) async {
  if (fullPageAd == null) {
    changeScreen();
    return;
  }

  WidgetsBinding.instance.addPostFrameCallback((_) async {
    if (fullPageAd != null) {
      fullPageAd!.fullScreenContentCallback = FullScreenContentCallback(
        onAdShowedFullScreenContent: (InterstitialAd ad) => {
          createInterstitialAd(),
          FirebaseAnalytics.instance.logEvent(
            name: "interstitialSHOW",
          ),
        },
        onAdDismissedFullScreenContent: (InterstitialAd ad) {
          ad.dispose();
        },
        onAdFailedToShowFullScreenContent: (InterstitialAd ad, AdError error) {
          ad.dispose();
          createInterstitialAd();
          FirebaseAnalytics.instance.logEvent(
            name: "interstitialFAILSHOW",
            parameters: {
              "errorReason": error.message,
            },
          );
        },
      );
      await fullPageAd!.show();
      fullPageAd = null;
    }
  });

  changeScreen();
}
```

```
Future<void> changeScreen() async {
    await Navigator.push(
      context,
      MaterialPageRoute(
          builder: (context) => SecondScreen()),
    );
}
```
Thanks to firebase logs i can see how many device can trigger the **onAdFailedToShowFullScreenContent**

![image](https://github.com/user-attachments/assets/8e759539-0db8-49d5-8b32-4270b90a5f15)

As you can see if the device is Android errorReason is **The ad can not be shown when app is not in foreground.**. If it is iOS, **the provided view controller is not being presented.**

Adding **WidgetsBinding.instance.addPostFrameCallback** reduced the errors (I just released new version we can't see on the chart) but it is still continuing. Google should fix this because it is reduces incomes significantly. I don't think it is because of my dart code it is pretty standart based on Google examples and also many users getting this error. Kind regards.

Note: Is it possible that those device may installed some kind of **AdBlocker** and that adblocker not prevent loading, but showing? Maybe we are getting this error because of that. AdBlock may be blocking the display of ads by putting the application in the background? Of course, this may only explain half of the error. I can't explain why this error also occur in iOS too.

Note2: Calling ads first, then navigate screen or visa-versa, DIDN'T WORK. Same error, nothing changed.

Note3: I added following tags to AndroidManifest.xml but it didn't change too. With or without error rate and reasons always same. (https://developers.google.com/admob/android/optimize-initialization)

```
<meta-data
   android:name="com.google.android.gms.ads.flag.OPTIMIZE_INITIALIZATION"
   android:value="true"/>
<meta-data
   android:name="com.google.android.gms.ads.flag.OPTIMIZE_AD_LOADING"
   android:value="true"/>
```

**Comment by peterweb2005** [comment]
no, my issue is only app open ad, and only in android

**Comment by aykutuludag** [comment]
> no, my issue is only app open ad, and only in android

Have you installed firebase analytics or similar technologies to your app for **verify nobody in your app experience this issue**? Because it is not happening my device I am seeing the ads but according to logs some device can't see the ads. It may currently happening your app too maybe. Also this issue is same for all fullscreen ads (open ad, interstitial

**Comment by peterweb2005** [comment]
> > no, my issue is only app open ad, and only in android
> 
> Have you installed firebase analytics or similar technologies to your app for **verify nobody in your app experience this issue**? Because it is not happening my device I am seeing the ads but according to logs some device can't see the ads. These data aggregated from nearly 50k devices both Android and iOS. It may currently happening your app too. Also this issue is same for all fullscreen ads (open ad, interstitial

yes, my side crash log all errors (not only ad; but skip network error which my app may retry), i see no count in interstitial ad showe error

you may have bug that there is 2 types of resume, 1 is flutter resume 
1 is admob resume

i may provide that later

**Comment by malandr2** [comment]
Hi @aykutuludag, we just released [`5.2.0`](https://pub.dev/packages/google_mobile_ads/changelog) which included an update to our full-screen presentation logic https://github.com/googleads/googleads-mobile-flutter/pull/1153

Can you confirm the errors you are seeing are happening for users that are running version `5.2.0` of the plugin?

**Comment by aykutuludag** [comment]
Yes I can confirm I'm still getting error  app is already integrated v5.2.0. Thanks to WidgetsBinding.instance.addPostFrameCallback errors reduced significantly but I am seeing on firebase console user's can't ads. Right now it is around %3-%5 of users can't see. Before addPostFrameCallback it rises up to %12.

**Comment by malandr2** [comment]
@aykutuludag got it. It's possible those errors are working as intended based on the integration. Can you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and I can take a look?

**Comment by aykutuludag** [comment]
I shared the minimal repdocible code in the first comment @malandr2 u can use that. I am calling showInterstitialAd function between screen changes. It is pretty standart implementation based on Google docs.

**Comment by peterweb2005** [comment]
yes, maybe same root cause, why there are 2 types of resume, and admob resume (foreground) very inaccurate

**Comment by aykutuludag** [comment]
> yes, maybe same root cause, why there are 2 types of resume, and admob resume (foreground) very inaccurate

Root cause seems to be same, like you said, Flutter Lifecycle and Admob Interstitial lifecycle is not coinciding all the time I guess.

**Comment by aykutuludag** [comment]
![image](https://github.com/user-attachments/assets/cf760557-f7d7-4553-bdc3-592183597ac5)

**Comment by aykutuludag** [comment]
New error: Web view content process terminated.

![image](https://github.com/user-attachments/assets/38e46e91-c8bc-4e4b-9204-ea68d0d51308)

**Comment by aykutuludag** [comment]
Yes I am showing ads beteen screen changes. changeScreen function is the responsible function to switching screens and it's code in the first comment too.

**Comment by malandr2** [comment]
Hi @aykutuludag, try calling `changeScreen() only after the interstitial ad is dismissed or fails to show. If `changeScreen()` is called before `show()` is called, it may throw an error

**Comment by aykutuludag** [comment]
> Hi @aykutuludag, try calling `changeScreen()` only after the interstitial ad is dismissed or fails to show. If `changeScreen()` is called before `show()` is called, it may throw an error

I'm trying to your solution and sending new version. Thanks I will notify about the issue.

**Comment by malandr2** [comment]
Hi @aykutuludag, if `changeScreen()` is called prior to `await fullPageAd!.show();` being called, that is likely a cause for errors to surface. Moving `changeScreen()` into the callbacks ensures the screen is not changed until the interstitial ad is shown. Theoretically could also try calling `changeScreen()` in [onAdShowedFullScreenContent](https://pub.dev/documentation/google_mobile_ads/latest/google_mobile_ads/FullScreenContentCallback/onAdShowedFullScreenContent.html) if `onAdDismissedFullScreenContent` is not optimal for your use case

**Comment by aykutuludag** [comment]
> Hi @aykutuludag, if `changeScreen()` is called prior to `await fullPageAd!.show();` being called, that is likely a cause for errors to surface. Moving `changeScreen()` into the callbacks ensures the screen is not changed until the interstitial ad is shown. Theoretically could also try calling `changeScreen()` in [onAdShowedFullScreenContent](https://pub.dev/documentation/google_mobile_ads/latest/google_mobile_ads/FullScreenContentCallback/onAdShowedFullScreenContent.html) if `onAdDismissedFullScreenContent` is not optimal for your use case

I tried inside of onAdShowedFullScreenContent, it didn't consistent. I applied inside of onAdDismissedFullScreenContent and now ad show fail reduced dramatically but not zero. I will write new error once new release obtained by more user. The delay is a little bit problematic in Android it is between 300ms-2sec. In iOS, it is almost unnoticeable it is about 150-300ms.

**Comment by aykutuludag** [comment]
Okay I am getting new errors. Bad news: Yeah the method you suggested **decreased** the rate of **onAdFailedToShowFullScreenContent** errors but **I am still getting it.**

For iOS: **the provided view controller is not being presented.**
For Android: **The ad can not be shown when app is not in foreground.**

Like I said it is decreased rate of the error significantly, but according to my early calculations it is still happen %3-5 of every session.

**Comment by malandr2** [comment]
Hi @aykutuludag, it's very possible these errors are completely valid based on how the user is interacting with your app. Small sample size is also possible. I don't imagine it will go down to 0% because users will still be running old versions. Seeing a sharp decrease is great news. I recommend to keep experimenting on the timing of when to present full-screen ads to your users. 

The callbacks are determined by the Google Mobile Ads Android and iOS SDKs, respectively. You can create a new thread in the [AdMob Developers forum](https://groups.google.com/g/google-admob-ads-sdk) to voice your feedback to the proper channels. 

Closing this out. Thanks!
