### ISSUE TITLE
Android ONLY: java.lang.IllegalStateException: PlatformView#getView() returned null, but an Android view reference was expected

### ISSUE THREAD

**Issue by figengungor** [googleads/googleads-mobile-flutter#46]
## Bug report

**Describe the bug**
Inline banner ad in a list cause crash on Android only.

### Steps to reproduce

1. Update dependency to 0.11.0+2 for google_mobile_ads & minSdk to 19 in (https://github.com/googlecodelabs/admob-inline-ads-in-flutter)
2. Increase sample items  x 3 which use for inline banner ad example
3. Scroll down until ad goes out of viewport, scroll up again and had this crash below on Android ONLY:

```
E/flutter (12339): [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(43)] java.lang.IllegalStateException: PlatformView#getView() returned null, but an Android view reference was expected.
E/flutter (12339): 	at io.flutter.plugin.platform.PlatformViewsController.initializePlatformViewIfNeeded(PlatformViewsController.java:710)
E/flutter (12339): 	at io.flutter.plugin.platform.PlatformViewsController.onDisplayPlatformView(PlatformViewsController.java:739)
E/flutter (12339): 	at io.flutter.embedding.engine.FlutterJNI.onDisplayPlatformView(FlutterJNI.java:957)
E/flutter (12339): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (12339): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter (12339): 	at android.os.Looper.loop(Looper.java:206)
E/flutter (12339): 	at android.app.ActivityThread.main(ActivityThread.java:8419)
E/flutter (12339): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (12339): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
E/flutter (12339): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
E/flutter (12339): 
F/flutter (12339): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1196)] Check failed: CheckException(env). 
F/libc    (12339): Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 12339 (.admobinlineads), pid 12339 (.admobinlineads)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/x1sxx/x1s:11/RP1A.200720.012/G980FXXU5CUA3:user/release-keys'
Revision: '22'
ABI: 'arm64'
Timestamp: 2021-03-06 16:01:56+0300
pid: 12339, tid: 12339, name: .admobinlineads  >>> com.codelab.flutter.admobinlineads <<<
uid: 10371
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1196)] Check failed: CheckException(env). 
'
    x0  0000000000000000  x1  0000000000003033  x2  0000000000000006  x3  0000007fecb68210
    x4  0000007e1e62f000  x5  0000007e1e62f000  x6  0000007e1e62f000  x7  0000000003736aa0
    x8  00000000000000f0  x9  344ba72bcf5be43a  x10 0000000000000000  x11 ffffffc0fffffbdf
    x12 0000000000000001  x13 0000000000000074  x14 0000000000000000  x15 00006f5640eaf8be
    x16 0000007e174bac80  x17 0000007e1749cc50  x18 0000007e1e61e000  x19 0000000000003033
    x20 0000000000003033  x21 00000000ffffffff  x22 0000007be6bae010  x23 0000000000000000
    x24 0000000000000438  x25 00000000000000d8  x26 0000000000000001  x27 0000007fecb68510
    x28 0000000000000085  x29 0000007fecb68290
    lr  0000007e17450624  sp  0000007fecb681f0  pc  0000007e17450650  pst 0000000000000000
backtrace:
      #00 pc 000000000004e650  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) (BuildId: b6a050117a93689b5308931507900b87)
      #01 pc 0000000001288244  /data/app/~~E_A6gdfKtuyBjx_ve83yBg==/com.codelab.flutter.admobinlineads-n5uEz5IUmmkCJXhBAs3vHw==/lib/arm64/libflutter.so (BuildId: 9c542952e0ea7b7a4b9c9734eda4f117db4285aa)
      #02 pc 00000000012792f4  /data/app/~~E_A6gdfKtuyBjx_ve83yBg==/com.codelab.flutter.admobinlineads-n5uEz5IUmmkCJXhBAs3vHw==/lib/arm64/libflutter.so (BuildId: 9c542952e0ea7b7a4b9c9734eda4f117db4285aa)
      #03 pc 00000000012cb534  /data/app/~~E_A6gdfKtuyBjx_ve83yBg==/com.codelab.flutter.admobinlineads-n5uEz5IUmmkCJXhBAs3vHw==/lib/arm64/libflutter.so (BuildId: 9c542952e0ea7b7a4b9c9734eda4f117db4285aa)
      #04 pc 00000000012be28c  /data/app/~~E_A6gdfKtuyBjx_ve83yBg==/com.codelab.flutter.admobinlineads-n5uEz5IUmmkCJXhBAs3vHw==/lib/arm64/libflutter.so (BuildId: 9c542952e0ea7b7a4b9c9734eda4f117db4285aa)
      #05 pc 00000000012beb60  /data/app/~~E_A6gdfKtuyBjx_ve83yBg==/com.codelab.flutter.admobinlineads-n5uEz5IUmmkCJXhBAs3vHw==/lib/arm64/libflutter.so (BuildId: 9c542952e0ea7b7a4b9c9734eda4f117db4285aa)
      #06 pc 00000000012bf4e0  /data/app/~~E_A6gdfKtuyBjx_ve83yBg==/com.codelab.flutter.admobinlineads-n5uEz5IUmmkCJXhBAs3vHw==/lib/arm64/libflutter.so (BuildId: 9c542952e0ea7b7a4b9c9734eda4f117db4285aa)
      #07 pc 00000000012be5c4  /data/app/~~E_A6gdfKtuyBjx_ve83yBg==/com.codelab.flutter.admobinlineads-n5uEz5IUmmkCJXhBAs3vHw==/lib/arm64/libflutter.so (BuildId: 9c542952e0ea7b7a4b9c9734eda4f117db4285aa)
      #08 pc 00000000012be398  /data/app/~~E_A6gdfKtuyBjx_ve83yBg==/com.codelab.flutter.admobinlineads-n5uEz5IUmmkCJXhBAs3vHw==/lib/arm64/libflutter.so (BuildId: 9c542952e0ea7b7a4b9c9734eda4f117db4285aa)
      #09 pc 00000000012bf718  /data/app/~~E_A6gdfKtuyBjx_ve83yBg==/com.codelab.flutter.admobinlineads-n5uEz5IUmmkCJXhBAs3vHw==/lib/arm64/libflutter.so (BuildId: 9c542952e0ea7b7a4b9c9734eda4f117db4285aa)
      #10 pc 0000000001288bbc  /data/app/~~E_A6gdfKtuyBjx_ve83yBg==/com.codelab.flutter.admobinlineads-n5uEz5IUmmkCJXhBAs3vHw==/lib/arm64/libflutter.so (BuildId: 9c542952e0ea7b7a4b9c9734eda4f117db4285aa)
      #11 pc 000000000128dc7c  /data/app/~~E_A6gdfKtuyBjx_ve83yBg==/com.codelab.flutter.admobinlineads-n5uEz5IUmmkCJXhBAs3vHw==/lib/arm64/libflutter.so (BuildId: 9c542952e0ea7b7a4b9c9734eda4f117db4285aa)
      #12 pc 0000000000019da8  /system/lib64/libutils.so (android::Looper::pollInner(int)+916) (BuildId: 4e69b93bf70ed592f0029dbd1097529e)
      #13 pc 00000000000199ac  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+112) (BuildId: 4e69b93bf70ed592f0029dbd1097529e)
      #14 pc 00000000001187f4  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44) (BuildId: 242a1c2f8c01c3530aee42ce4254ec53)
      #15 pc 000000000024f00c  /system/framework/arm64/boot-framework.oat (art_jni_trampoline+140) (BuildId: ba616edc5d43a5ad71e513e266d2e93e004cfa2e)
      #16 pc 00000000020019bc  /memfd:jit-cache (deleted) (offset 0x2000000) (android.os.MessageQueue.next+204)
      #17 pc 0000000000134564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: 1e59dbd15c62f521119299bf54dfe884)
      #18 pc 00000000001a9a78  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200) (BuildId: 1e59dbd15c62f521119299bf54dfe884)
      #19 pc 0000000000320d60  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+376) (BuildId: 1e59dbd15c62f521119299bf54dfe884)
      #20 pc 000000000031708c  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+996) (BuildId: 1e59dbd15c62f521119299bf54dfe884)
      #21 pc 0000000000684870  /apex/com.android.art/lib64/libart.so (MterpInvokeVirtual+848) (BuildId: 1e59dbd15c62f521119299bf54dfe884)
      #22 pc 000000000012e814  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: 1e59dbd15c62f521119299bf54dfe884)
      #23 pc 000000000044caf2  /system/framework/framework.jar (offset 0x9cb000) (android.os.Looper.loop+154)
      #24 pc 000000000030e688  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.8133272982542804073)+268) (BuildId: 1e59dbd15c62f521119299bf54dfe884)
      #25 pc 0000000000316678  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+200) (BuildId: 1e59dbd15c62f521119299bf54dfe884)
      #26 pc 0000000000317a60  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, true>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+1772) (BuildId: 1e59dbd15c62f521119299bf54dfe884)
      #27 pc 0000000000178f40  /apex/com.android.art/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<true, false>(art::interpreter::SwitchImplContext*)+57848) (BuildId: 1e59dbd15c62f521119299bf54dfe884)
      #28 pc 00000000001407d8  /apex/com.android.art/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: 1e59dbd15c62f521119299bf54dfe884)
      #29 pc 00000000001cd564  /system/framework/framework.jar (android.app.ActivityThread.main)
      #30 pc 000000000030e790  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.8133272982542804073)+532) (BuildId: 1e59dbd15c62f521119299bf54dfe884)
      #31 pc 00000000006732f4  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+780) (BuildId: 1e59dbd15c62f521119299bf54dfe884)
      #32 pc 000000000013dff8  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: 1e59dbd15c62f521119299bf54dfe884)
      #33 pc 00000000001347e8  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+568) (BuildId: 1e59dbd15c62f521119299bf54dfe884)
      #34 pc 00000000001a9a94  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+228) (BuildId: 1e59dbd15c62f521119299bf54dfe884)
      #35 pc 000000000055d2a0  /apex/com.android.art/lib64/libart.so (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1364) (BuildId: 1e59dbd15c62f521119299bf54dfe884)
      #36 pc 00000000004dc60c  /apex/com.android.art/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+52) (BuildId: 1e59dbd15c62f521119299bf54dfe884)
      #37 pc 000000000008a6f4  /apex/com.android.art/javalib/arm64/boot.oat (art_jni_trampoline+180) (BuildId: cf3195be2d1e729ad27299071d73c22f0d849b44)
      #38 pc 0000000000134564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: 1e59dbd15c62f521119299bf54dfe884)
      #39 pc 00000000001a9a78  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200) (BuildId: 1e59dbd15c62f521119299bf54dfe884)
      #40 pc 0000000000320d60  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+376) (BuildId: 1e59dbd15c62f521119299bf54dfe884)
      #41 pc 000000000031708c  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+996) (BuildId: 1e59dbd15c62f521119299bf54dfe884)
      #42 pc 0000000000684870  /apex/com.android.art/lib64/libart.so (MterpInvokeVirtual+848) (BuildId: 1e59dbd15c62f521119299bf54dfe884)
      #43 pc 000000000012e814  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: 1e59dbd15c62f521119299bf54dfe884)
      #44 pc 0000000000236df6  /system/framework/framework.jar (offset 0x1c0c000) (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+22)
      #45 pc 000000000030e688  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.8133272982542804073)+268) (BuildId: 1e59dbd15c62f521119299bf54dfe884)
      #46 pc 00000000006732f4  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+780) (BuildId: 1e59dbd15c62f521119299bf54dfe884)
      #47 pc 000000000013dff8  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: 1e59dbd15c62f521119299bf54dfe884)
      #48 pc 0000000000afbfac  /system/framework/arm64/boot-framework.oat (com.android.internal.os.ZygoteInit.main+2444) (BuildId: ba616edc5d43a5ad71e513e266d2e93e004cfa2e)
      #49 pc 00000000001347e8  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+568) (BuildId: 1e59dbd15c62f521119299bf54dfe884)
      #50 pc 00000000001a9a94  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+228) (BuildId: 1e59dbd15c62f521119299bf54dfe884)
      #51 pc 000000000055bcdc  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, std::__va_list)+448) (BuildId: 1e59dbd15c62f521119299bf54dfe884)
      #52 pc 000000000055c190  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+92) (BuildId: 1e59dbd15c62f521119299bf54dfe884)
      #53 pc 0000000000440b94  /apex/com.android.art/lib64/libart.so (art::JNI<true>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+656) (BuildId: 1e59dbd15c62f521119299bf54dfe884)
      #54 pc 000000000009d424  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+124) (BuildId: 242a1c2f8c01c3530aee42ce4254ec53)
      #55 pc 00000000000a5244  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+848) (BuildId: 242a1c2f8c01c3530aee42ce4254ec53)
      #56 pc 0000000000003594  /system/bin/app_process64 (main+1356) (BuildId: 1b1b967ddfe0761f978fc1b2bd9ea55a)
      #57 pc 0000000000049a38  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+108) (BuildId: b6a050117a93689b5308931507900b87)
Lost connection to device.
```
`

### Expected behavior

No crash.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by mileusna** [comment]
I can confirm this. Release 0.11.0+2 fixed #36 but now app will crash on Andorid with ad in ScrollView, usually when you scroll back to the ad (in same occasion where #36 was shown in 0.11.0+1 release). But only on Android, it looks like everything is working OK on iOS.

When I recomple the code using closed beta package version I used before, everything is forking fine. With 0.11.0+2 it will crash on Andorid.

**Comment by jjliu15** [comment]
Opened https://github.com/googleads/googleads-mobile-flutter/pull/64 to address this crash.

**Comment by jjliu15** [comment]
Should be fixed in 0.11.0+3

**Comment by songyiYu** [comment]
@jjliu15  I still get this error in 0.11.0+3. Android sdk version is 4.4

**Comment by Purus** [comment]
Still this is happening in the latest version too.

**Comment by Purus** [comment]
It was all fine with banner and full screen ads. but this issue occurs when using native ads.

**Comment by franciscocpg** [comment]
Same error here using banner ad and `google_mobile_ads: ^0.12.1`:

```
I/flutter (25718): Ad load failed (code=3 message=No ad config.)
I/flutter (25718): Ad load failed (code=3 message=No ad config.)
I/flutter (25718): Ad load failed (code=3 message=No ad config.)
I/flutter (25718): Ad load failed (code=3 message=No ad config.)
I/flutter (25718): Ad load failed (code=3 message=No ad config.)
I/flutter (25718): Ad load failed (code=3 message=No ad config.)
I/flutter (25718): Ad load failed (code=3 message=No ad config.)
I/flutter (25718): Ad load failed (code=3 message=No ad config.)
I/flutter (25718): Ad load failed (code=3 message=No ad config.)
I/flutter (25718): Ad load failed (code=1 message=Error building request URL.)
I/flutter (25718): Ad load failed (code=1 message=Error building request URL.)
I/flutter (25718): Ad load failed (code=1 message=Error building request URL.)
I/flutter (25718): Ad load failed (code=1 message=Error building request URL.)
I/flutter (25718): Ad load failed (code=1 message=Error building request URL.)
I/flutter (25718): Ad load failed (code=1 message=Error building request URL.)
I/flutter (25718): Ad load failed (code=1 message=Error building request URL.)
I/flutter (25718): Ad load failed (code=1 message=Error building request URL.)
I/flutter (25718): Ad load failed (code=1 message=Error building request URL.)
E/flutter (25718): [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(49)] java.lang.IllegalStateException: PlatformView#getView() returned null, but an Android view reference was expected.
E/flutter (25718):      at io.flutter.plugin.platform.k.a()
E/flutter (25718):      at io.flutter.plugin.platform.k.a()
E/flutter (25718):      at io.flutter.embedding.engine.FlutterJNI.onDisplayPlatformView()
E/flutter (25718):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (25718):      at android.os.MessageQueue.next(MessageQueue.java:323)
E/flutter (25718):      at android.os.Looper.loop(Looper.java:136)
E/flutter (25718):      at android.app.ActivityThread.main(ActivityThread.java:6349)
E/flutter (25718):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter (25718):      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
E/flutter (25718):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
E/flutter (25718): 
F/flutter (25718): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1395)] Check failed: CheckException(env). 
Application finished.
```

**Comment by thize** [comment]
Same error here using banner ad and google_mobile_ads: ^0.12.1

**Comment by franciscocpg** [comment]
In my case, I was able to fix it by removing the call to `ad.dispose()` at the `onAdFailedToLoad` listener.

**Comment by SidneyMachara** [comment]
Same error trying to create a simple native ad from the example --> google_mobile_ads: ^0.12.1+1

**Comment by Armoured-Door-Studio** [comment]
> .disp

Your sir, just saved me.

**Comment by Armoured-Door-Studio** [comment]
> In my case, I was able to fix it by removing the call to `ad.dispose()` at the `onAdFailedToLoad` listener.

Your sir, just saved me.

**Comment by shofizone** [comment]
I am having the same error.  The app is crashing in debug mode while the **internet** is turned off. 
`  google_mobile_ads: ^0.12.1+1`
```
[ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(49)] java.lang.IllegalStateException: PlatformView#getView() returned null, but an Android view reference was expected.
E/flutter (25518): 	at io.flutter.plugin.platform.PlatformViewsController.initializePlatformViewIfNeeded(PlatformViewsController.java:717)
E/flutter (25518): 	at io.flutter.plugin.platform.PlatformViewsController.onDisplayPlatformView(PlatformViewsController.java:746)
E/flutter (25518): 	at io.flutter.embedding.engine.FlutterJNI.onDisplayPlatformView(FlutterJNI.java:1195)
E/flutter (25518): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (25518): 	at android.os.MessageQueue.next(MessageQueue.java:331)
E/flutter (25518): 	at android.os.Looper.loop(Looper.java:149)
E/flutter (25518): 	at android.app.ActivityThread.main(ActivityThread.java:6651)
E/flutter (25518): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (25518): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/flutter (25518): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
E/flutter (25518): 
F/flutter (25518): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1395)] Check failed: CheckException(env). 
F/libc    (25518): Fatal signal 6 (SIGABRT), code -6 in tid 25518 (ideo_compressor), pid 25518 (ideo_compressor)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'xiaomi/vince/vince:8.1.0/OPM1.171019.019/V11.0.2.0.OEGMIXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 25518, tid: 25518, name: ideo_compressor  >>> com.freeconvert.video_compressor <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1395)] Check failed: CheckException(env). 
'
    x0   0000000000000000  x1   00000000000063ae  x2   0000000000000006  x3   0000000000000008
    x4   0000000000000000  x5   0000000000000000  x6   0000000000000000  x7   0000800000000000
    x8   0000000000000083  x9   20e082fbd6042fe0  x10  0000000000000000  x11  0000000000000001
    x12  ffffffffffffffff  x13  0000000000000010  x14  ffffffffffffffff  x15  000063bb69aa0744
    x16  0000005b450c2fa8  x17  00000077a58ff5d8  x18  0000000070001ec0  x19  00000000000063ae
    x20  00000000000063ae  x21  0000007fcd403888  x22  0000007722ccd2a0  x23  00000076f6210778
    x24  0000000000000437  x25  0000000000000089  x26  0000000000000000  x27  0000007fcd403ac0
    x28  0000000000000081  x29  0000007fcd403860  x30  00000077a58b4e38
    sp   0000007fcd403820  pc   00000077a58b4e54  pstate 0000000060000000
backtrace:
    #00 pc 000000000001de54  /system/lib64/libc.so (abort+104)
    #01 pc 0000000000002404  /data/app/com.freeconvert.video_compressor-0EmvnxFiKfFo4q5l0DEtDg==/lib/arm64/libflutter.so (offset 0x131f000)
```

**Comment by jnknewaj** [comment]
> In my case, I was able to fix it by removing the call to `ad.dispose()` at the `onAdFailedToLoad` listener.

Not fixed here. Any other solution?

**Comment by shofizone** [comment]
> > In my case, I was able to fix it by removing the call to `ad.dispose()` at the `onAdFailedToLoad` listener.
> 
> Not fixed here. Any other solution?

Initially, I was facing the same issue. The problem was UI is trying to load the banner ads while the ad is not ready yet. To check just turn off the internet then try to run the app in debug mode. If the app is crashed then your problem is the same as mine.  So you shouldn't try to load the while ad is not ready. to fix it just follow the example of this [repo](https://github.com/googleads/googleads-mobile-flutter/tree/master/packages/google_mobile_ads/example). They have a very good example of those cases.

**Comment by adamlamoglia** [comment]
Same error here using Native Ad --> google_mobile_ads: ^0.12.1+1

**Comment by shazlycode** [comment]
> In my case, I was able to fix it by removing the call to `ad.dispose()` at the `onAdFailedToLoad` listener.

thank you, works for me

**Comment by blasten** [comment]
This is a race condition caused by calling `destroy()` in https://github.com/googleads/googleads-mobile-flutter/blob/a2c7afe02bcb9f5f03cbf81d271dd4c5b24600be/packages/google_mobile_ads/android/src/main/java/io/flutter/plugins/googlemobileads/FlutterBannerAd.java#L85-L88, and then `getView()`. 

@jjliu15 @bparrishMines could we prioritize this issue?

**Comment by way2anash** [comment]
> In my case, I was able to fix it by removing the call to `ad.dispose()` at the `onAdFailedToLoad` listener.

Thanks a lot, this tip of yours saved my day.

**Comment by SnehModi** [comment]
> Initially, I was facing the same issue. The problem was UI is trying to load the banner ads while the ad is not ready yet. To check just turn off the internet then try to run the app in debug mode. If the app is crashed then your problem is the same as mine. So you shouldn't try to load the while ad is not ready. to fix it just follow the example of this [repo](https://github.com/googleads/googleads-mobile-flutter/tree/master/packages/google_mobile_ads/example). They have a very good example of those cases.

I agree with you. You have been very helpful. Actually, instead of adding a listener, if we can get a NativeAd only after it is ready or an Error thrown if the ad cannot be loaded, it would be a lot more simpler.

See, the issue is that sometimes, we need to load the ads one after another and based on some event. It becomes difficult to do so when we cannot separate the code for NativeAd from our stateful widget. I would find it much easier to write a separate code for loading Ads rather than having it entwined with my stateful widget which needs to be rebuild on various different occasions based on our requirements.

**Comment by jjliu15** [comment]
This should be fixed by https://github.com/googleads/googleads-mobile-flutter/pull/263, in the latest v0.13.2 release. 
Also maybe worth noting that in v0.13.0 you no longer need to call `dispose()` when an ad fails to load, which should also help with this issue.

**Comment by lucianocheng** [comment]
This is still happening for v0.13.5:

```
I/flutter ( 9856): CacheManager: Failed to download file from https://storage.googleapis.com/minecraft-fast/banners_webp/play|histeria|fr:19132.webp with error:
I/flutter ( 9856): HttpException: Invalid statusCode: 404, uri = https://storage.googleapis.com/minecraft-fast/banners_webp/play%7Chisteria%7Cfr:19132.webp
E/flutter ( 9856): [ERROR:flutter/fml/platform/android/jni_util.cc(182)] java.lang.IllegalStateException: The Android view returned from PlatformView#getView() was already added to a parent view.
E/flutter ( 9856): 	at io.flutter.plugin.platform.PlatformViewsController.initializePlatformViewIfNeeded(PlatformViewsController.java:744)
E/flutter ( 9856): 	at io.flutter.plugin.platform.PlatformViewsController.onDisplayPlatformView(PlatformViewsController.java:792)
E/flutter ( 9856): 	at io.flutter.embedding.engine.FlutterJNI.onDisplayPlatformView(FlutterJNI.java:1245)
E/flutter ( 9856): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 9856): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter ( 9856): 	at android.os.Looper.loop(Looper.java:183)
E/flutter ( 9856): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/flutter ( 9856): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 9856): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/flutter ( 9856): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter ( 9856): 
F/flutter ( 9856): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1384)] Check failed: fml::jni::CheckException(env). 
```
