### ISSUE TITLE
Low performance with Flutter 3 on iOS devices

### ISSUE THREAD

**Issue by marcellocamara** [googleads/googleads-mobile-flutter#574]
I found performance issues with `Flutter 3.0.1`, with `Dart 2.17.1`, using the `google_mobile_ads 1.2.0` on iOS.

Obs.: Using **LARGE_BANNER** ad. 
I think this is realted to `google_mobile_ads` and `iOS`. Android works pretty well, without any issues.

## Evidence video

https://user-images.githubusercontent.com/18273071/170879694-b6874cce-69c7-41bc-807b-88b1335783a8.mp4

## Plugin Version

google_mobile_ads: ˆ1.2.0

## Steps to Reproduce

1. Create some example app using flutter 3.0.1
2. Add google_mobile_ads version 1.2.0 and use Banner Ad on different pages of your app.
3. Navigate between pages with real banners ids - on TEST MODE (simulates real ads)

**Expected results:** Fluid navigation

**Actual results:** Performance issues

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-x64, locale pt-BR)
    • Flutter version 3.0.1 at /Users/cello/fvm/versions/3.0.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (6 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/cello/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/cello/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.4 21F79 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by maheshmnj** [comment]
Hi @marcellocamara, Thanks for filing the issue. Pleas ensure that you are disposing off the widgets (including the ad widget)on popping the route, I tried with the below code sample  on a simulator and it seems to work fine. Can you please confirm if the issue reproduces with the code sample I shared? if it doesn't then please share a minimal and complete code sample to investigate further. Also is this issue only on IOS or Android too?

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:google_mobile_ads/google_mobile_ads.dart';

class TelaResultado extends StatefulWidget {
  final resultado;

  const TelaResultado({Key? key, required this.resultado}) : super(key: key);

  @override
  State<TelaResultado> createState() => _TelaResultadoState();
}

class _TelaResultadoState extends State<TelaResultado> {
  // Anuncios
  BannerAd? _anchoredAdaptiveAd;
  bool _isLoaded = false;
  late Orientation _currentOrientation;

  static const AdRequest request = AdRequest(
    keywords: <String>['foo', 'bar'],
    contentUrl: 'http://foo.com/bar.html',
    nonPersonalizedAds: true,
  );

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    _currentOrientation = MediaQuery.of(context).orientation;
    _loadAd();
  }

  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    super.dispose();
    _anchoredAdaptiveAd?.dispose();
  }

  Future<void> _loadAd() async {
    setState(() {
      _anchoredAdaptiveAd = null;
      _isLoaded = false;
    });

    final AnchoredAdaptiveBannerAdSize? size =
        await AdSize.getCurrentOrientationAnchoredAdaptiveBannerAdSize(
            MediaQuery.of(context).size.width.truncate());

    if (size == null) {
      print('Unable to get height of anchored banner.');
      return;
    }

    _anchoredAdaptiveAd = BannerAd(
      adUnitId: 'ca-app-pub-3940256099942544/630097811',
      size: size,
      request: request,
      // listener: const BannerAdListener(),
      listener: BannerAdListener(
        onAdLoaded: (Ad ad) {
          print('$ad loaded: ${ad.responseInfo}');
          setState(() {
            // When the ad is loaded, get the ad size and use it to set
            // the height of the ad container.
            _anchoredAdaptiveAd = ad as BannerAd;
            _isLoaded = true;
          });
        },
        onAdFailedToLoad: (Ad ad, LoadAdError error) {
          print('Anchored adaptive banner failedToLoad: $error');
          ad.dispose();
        },
      ),
    );
    await _anchoredAdaptiveAd!.load();
    setState(() {
      _isLoaded = true;
    });
  }

  Widget _getAdWidget() {
    return OrientationBuilder(
      builder: (context, orientation) {
        if (_currentOrientation == orientation &&
            _anchoredAdaptiveAd != null &&
            _isLoaded) {
          return Container(
            // color: Colors.green,
            width: _anchoredAdaptiveAd!.size.width.toDouble(),
            height: _anchoredAdaptiveAd!.size.height.toDouble(),
            child: AdWidget(ad: _anchoredAdaptiveAd!),
          );
        }
        // Reload the ad if the orientation changes.
        if (_currentOrientation != orientation) {
          _currentOrientation = orientation;
          _loadAd();
        }
        return Container(
          height: 100,
          color: Colors.red,
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Quiz Bíblico"),
      ),
      body: Container(
        child: Column(
          children: [
            _getAdWidget(),
            Expanded(
              child: Center(
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Image.asset(
                      "assets/flutter_engage.jpeg",
                      width: 200,
                      height: 200,
                    ),
                    Padding(
                      padding: const EdgeInsets.all(8.0),
                      child: Text(
                        "Resultado: ${widget.resultado}",
                        style:
                            const TextStyle(fontSize: 20, color: Colors.black),
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

void main() {
  WidgetsFlutterBinding.ensureInitialized();

  //Running the app without the below code will print the device id in log cat
  MobileAds.instance.updateRequestConfiguration(
      RequestConfiguration(testDeviceIds: ['INSERT TEST DEVICE ID HERE']));

  MobileAds.instance.initialize();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        home: const MyHomePage(
          title: 'Home Screen',
        ));
  }
}

class MyHomePage extends StatefulWidget {
  final String title;
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late BannerAd bannerAd;
  bool adsLoaded = false;

  @override
  void initState() {
    initializeAd();
    super.initState();
  }

  initializeAd() async {
    bannerAd = BannerAd(
      adUnitId:
          'ca-app-pub-3940256099942544/6300978111', // <- This is an ANDROID test ad unit id
      size: AdSize.banner,
      request: const AdRequest(),
      listener: const BannerAdListener(),
    );
    bannerAd.load();
    setState(() {
      adsLoaded = true;
    });
  }

  @override
  void dispose() {
    bannerAd.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("${widget.title}"),
      ),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.spaceAround,
        children: [
          const Placeholder(fallbackHeight: 300),
          SizedBox(
            child: AdWidget(
              ad: bannerAd,
            ),
            width: bannerAd.size.width.toDouble(),
            height: bannerAd.size.height.toDouble(),
          ),
          ElevatedButton(
              onPressed: () {
                Navigator.of(context).push(MaterialPageRoute(
                    builder: (context) =>
                        const MyHomePage(title: 'Second Page')));
              },
              child: Text('navigate'))
        ],
      ),
    );
  }
}

```
</details>   

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3 21E230 darwin-arm, locale en-IN)
    • Flutter version 3.0.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (3 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin
        usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555                     • android-arm64  • Android 11 (API 30)
    • iPhone 12 Pro (mobile) • 19FD0231-BFF0-441D-B584-AD94C4084525 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```
</details>

**Comment by marcellocamara** [comment]
@maheshmnj I think I cannot test your code, due to necessary have certifies/profile to run on physical device (and I don't have it)

The performance error appears only on physical devices. In simulator it is not reproducible
It should be tested with real banner ads on real device.

**Comment by adrianlogue** [comment]
I had the same issue and could reproduce it running a debug build on a real device with real ads - and only occurs on iOS.

It occurs when the ad moves across the screen because of some animation (like the navigation transition animation in the @marcellocamara video above). In my case it is when the software keyboard appears and pushes the ad up from the bottom of the screen. The debug console rapidly fills with hundreds of the following logs:

`[WindowServer] CADisplayTimingsControl too many requests.
[WindowServer] Unmatched CAFrameIntervalRange unregistration.`

Within a minute or two performance declines and the logs start to fire hundreds of times a second and most touch interactions are followed by 10 to 20 secs of screen freeze.

Those specific errors indicate it may be related to 120hz refresh rate introduced with ProMotion in iOS 15.x.

For me it was resolved by converting the widget that serves the ad to be a Stateful widget and then ensuring the ad is disposed along the lines of the code sample supplied by @maheshmnj.

**Comment by maheshmnj** [comment]
thanks for the update @marcellocamara, Can you please share a timeline trace JSON file which should help us identify the cause of the issue?

you can find the instructions here https://github.com/flutter/flutter/issues/74833

**Comment by eric610** [comment]
I'm currently developing a flutter web app with flutter 3.1 and I have to say that the animation is extremely laggy for scrolling listivew.builder , any way I can make it smooth ?? Or should I just abandon flutter web totally ??

**Comment by maheshmnj** [comment]
@eric610 If you would like to report it, You should be filing that issue at http://github.com/flutter/flutter and we would love to investigate. This repo is mainly to file issues related to google_mobile_ads

**Comment by marcellocamara** [comment]
@maheshmnj 
> Can you please share a timeline trace JSON file which should help us identify the cause of the issue?

I did not understand how to open the observatory functionality, as the doc says. The tutorial is very old and Android studio have been changed.

I've runned my app on profile mode (debug mode error not appears, only profile and release mode). 

I noticed that only when the perfomance error appears the log shows up:
```
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
[assertion] Error acquiring assertion: <Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}>
[ProcessSuspension] 0x118004d20 - ProcessAssertion: Failed to acquire RBS assertion 'WebProcess Background Assertion' for process with PID=89139, error: Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}
[assertion] Error acquiring assertion: <Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}>
[ProcessSuspension] 0x118004de0 - ProcessAssertion: Failed to acquire RBS assertion 'ConnectionTerminationWatchdog' for process with PID=89139, error: Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}
[assertion] Error acquiring assertion: <Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}>
[ProcessSuspension] 0x118004e40 - ProcessAssertion: Failed to acquire RBS assertion 'WebProcess Suspended Assertion' for process with PID=89139, error: Error Domain=RBSServiceErrorDomain Code=1 "target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit" UserInfo={NSLocalizedFailureReason=target is not running or doesn't have entitlement com.apple.runningboard.assertions.webkit}
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
```

**Comment by marcellocamara** [comment]
@maheshmnj here it is:

[dart-timeline-2022-6-11.json.zip](https://github.com/googleads/googleads-mobile-flutter/files/8884777/dart-timeline-2022-6-11.json.zip)

Ps.: I think the worst performance issue is when the tag "Test mode" shows on the banner. On this test made, the tag didn't show but has issues

**Comment by jjliu15** [comment]
Hi @marcellocamara, could you also share a code sample of the widget that is showing the banner ad?

**Comment by marcellocamara** [comment]
> could you also share a code sample of the widget that is showing the banner ad?

Sure, @jjliu15 :

I'm using `google_mobile_ads: ^1.3.0`, `shimmer: ^2.0.0` with `Flutter 3.0.1` and `Dart 2.17.1`

My custom Banner Widget:
```
class CustomAdBannerWidget extends StatefulWidget {
  final AdSize adSize;
  final bool canBeInvisible;
  final double paddingTop;
  final double paddingBottom;

  CustomAdBannerWidget({
    this.adSize = AdSize.largeBanner,
    this.canBeInvisible = true,
    this.paddingTop = 20,
    this.paddingBottom = 20,
  });

  @override
  _CustomAdBannerWidgetState createState() => _CustomAdBannerWidgetState();
}

class _CustomAdBannerWidgetState extends State<CustomAdBannerWidget> {
  /// Visibility var
  bool _loading = true;
  bool _loaded = true;

  double get _width => widget.adSize.width.toDouble();

  double get _height => widget.adSize.height.toDouble();

  BannerAd? _bannerAd;

  @override
  void initState() {
    super.initState();
    _bannerAd = BannerAd(
      size: widget.adSize,
      request: const AdRequest(),
      adUnitId: AdmobUtils.bannerId,
      listener: BannerAdListener(
        onAdLoaded: (Ad ad) {
          setState(() {
            _bannerAd = ad as BannerAd?;
            _loading = false;
          });
        },
        onAdFailedToLoad: (Ad ad, LoadAdError error) {
          ad.dispose();
          setState(() => _loaded = false);
        },
      ),
    )..load();
  }

  @override
  void dispose() {
    _bannerAd?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Visibility(
      visible: _loaded,
      child: Container(
        padding: EdgeInsets.only(
          top: widget.paddingTop,
          bottom: widget.paddingBottom,
        ),
        alignment: Alignment.bottomCenter,
        child: _loading || _bannerAd == null
            ? CustomShimmerWidget(width: _width, height: _height)
            : SizedBox(
                width: _width,
                height: _height,
                child: AdWidget(ad: _bannerAd!),
              ),
      ),
    );
  }
}
```

Custom Shimmer:
```
class CustomShimmerWidget extends StatelessWidget {
  final double height, width;
  final double borderRadius;

  CustomShimmerWidget({
    required this.height,
    required this.width,
    this.borderRadius = 0,
  });

  @override
  Widget build(BuildContext context) {
    final brightness = Theme.of(context).brightness;
    return Shimmer.fromColors(
      baseColor:
          brightness == Brightness.light ? Colors.grey[300]! : Colors.white12,
      highlightColor:
          brightness == Brightness.light ? Colors.grey[100]! : Colors.white38,
      period: const Duration(seconds: 1),
      child: Container(
        height: height,
        width: width,
        decoration: BoxDecoration(
          shape: BoxShape.rectangle,
          borderRadius: BorderRadius.circular(borderRadius),
          color: brightness == Brightness.light ? Colors.grey : Colors.white70,
        ),
      ),
    );
  }
}
```

Evidence debugging on simulator with the "Test mode" enabled:

https://user-images.githubusercontent.com/18273071/174199452-a83e0405-9a94-4611-b270-a0872539445b.mov

**Comment by dayron9110** [comment]
some workaround  o news?

**Comment by dayron9110** [comment]
With Flutter 3.0 the performance on iOS is so bad...

**Comment by ajdll5-dev** [comment]
some workaround or news.....?

**Comment by b3nni97** [comment]
A P1 now gives me some hope that this problem will eventually be solved

**Comment by DavideM12** [comment]
Is there any news about? :(

**Comment by timothyhoang-google** [comment]
@marcellocamara - Are you loading a new ad every time the view loads in your video example (Ads.causes.low.performance.on.iOS.mov)?

**Comment by marcellocamara** [comment]
@timothyhoang-google yes. every page has differente banner id associated (granularity, making it possible to know the receipt of each area inside the app)

**Comment by timothyhoang-google** [comment]
@marcellocamara - thanks for confirming. So the views for "Perfil" and "Ajustes" each have ad placements with distinct ad unit IDs.

What happens when you switch between "Perfil" and "Ajustes" and back: "Perfil" -> "Ajustes" -> "Perfil". Do you call load() 3 times?

In this additional example: "Perfil" -> "Ajustes" -> "Perfil" -> "Ajustes" -> "Perfil", is load() called 5 times?

**Comment by marcellocamara** [comment]
@timothyhoang-google yes, the pages doesn't keep alive. so, everytime when open any page, loads the ad

on my first video, of another app - the first one on this thread - filmed, I used the same banner id to load the ad on the new page pushed to the stack ("Ajustes" -> "Aparência")

**Comment by timothyhoang-google** [comment]
Loading ads via the GMA SDK is an 'expensive' operation in that it uses the UI thread. When load() is called, the GMA SDK forms and sends ad request, parses the ad response once it's received, and renders an ad if there is fill. It's not recommended to call load() several times in quick succession, as this can interfere with other operations that utilize the UI thread.

We recommend caching the ad once it's loaded for a single view and re-using it within a short period of time. For example, if the user visits "Perfil" -> "Ajustes" -> "Perfil" -> "Ajustes" -> "Perfil", you would load the ad only twice instead of five times. You can refresh the cache after a few seconds if you want new ads.

As an additional note, also ensure you're calling dispose() when access is no longer needed to an instance of the banner ad.

**Comment by marcellocamara** [comment]
@timothyhoang-google 
> It's not recommended to call load() several times in quick succession, as this can interfere with other operations that utilize the UI thread.

Sure, but in already loaded pages, if you scroll down and up you can observe a low performance - just on **iOS**. The switching pages is just a easy way to see this problem.

> We recommend caching the ad once it's loaded for a single view and re-using it within a short period of time

Would you have any example of this ? Should use static method to return the static banner ad ?

> As an additional note, also ensure you're calling dispose()

Yes, I'm disposing it

This related problem does not is reproducible on Android

**Comment by timothyhoang-google** [comment]
> Sure, but in already loaded pages, if you scroll down and up you can observe a low performance - just on iOS. The switching pages is just a easy way to see this problem.

I think updating the view based on scrolling still uses the UI thread even if the view has already been loaded. Additionally, if there are elements that are being lazy loaded as you scroll, performance would still be impacted if load() is being called multiple times concurrently.

Are you seeing performance issues when scrolling with only a single inline ad in the page? We generally see this issue if the ad density in a scroll view is high (e.g. visual search feed with ad placements interleaved). For this we only recommend that ads are spaced so that only one is visible in the viewport at once (in addition to recycling scroll elements and caching ads).

> Would you have any example of this ? Should use static method to return the static banner ad ?

For banners, the recommendation would be to load your banner early in your app's lifecycle (e.g. myBanner.load()) and then keep a reference to it. There are many ways to cache the ad, but keeping a reference to it would be sufficient.

When the ad is ready to show, you would attach it to the widget tree. There's no static method like show() to call.

If doing this doesn't resolve your issue, let me know.

**Comment by SufianHamoudi** [comment]
I am having the exact same issue on my iPhone 13 Pro Max . And it is 100% related to Flutter 3.0's support for 120Hz on the new iPhone 13 pro/max.

I made sure of what I said in the first line by disabling Pro Motion from Accessibility settings under Settings>Accessibility>Motion>Limit Frame Rate(on). When Limit Frame Rate setting is on, the problem disappears. After re-disabling it, the problem appears again.

I hope that the Flutter devs are already aware of this problem and that they are already working on a fix.

**Comment by timothyhoang-google** [comment]
> I am having the exact same issue on my iPhone 13 Pro Max with google_mobile_ads . And it is 100% related to Flutter 3.0's support for 120Hz on the new iPhone 13 pro/max.

> I made sure of what I said in the first line by disabling Pro Motion from Accessibility settings under Settings>Accessibility>Motion>Limit Frame Rate(on). When Limit Frame Rate setting is on, the problem disappears. After re-disabling it, the problem appears again.

> I hope that the Flutter devs are already aware of this problem and that they are already working on a fix.

@bparrishMines - FYI

**Comment by cyanglaz** [comment]
I wonder if it is similar to https://github.com/flutter/flutter/issues/101653. For testing purpose, we can try to add a CADisplayLink on the thread where the ads renders and set it to be 120hz, see if the issue is fixed.

**Comment by cyanglaz** [comment]
Is there a simplified code that can be used to reproduce this issue?

**Comment by cyanglaz** [comment]
From my testing with the code sample here: https://github.com/googleads/googleads-mobile-flutter/issues/574#issuecomment-1141151105. 
I can see the ads took some time to load, is it expected that ads would take some time to load (depending on the network speed?)
I couldn't see the issue where the page freeze during navigation. 

Is there a reduced test case where I can use to reproduce the freeze issue?

**Comment by marcellocamara** [comment]
@cyanglaz It's important to note that this bug appears only in release mode with real ads (I don't know if the tag "Test mode" on the Ad changes something). Debug mode is not reproducible

**Comment by cyanglaz** [comment]
I couldn't reproduce the visual jank issue on iPhone X and iPhone 13 pro with iOS 16.1.1, flutter 3.0.1, google_mobile_ads 1.2.0.
The ads sometimes took some time to load and I'm not sure if that is expected.

See recorded video:


https://user-images.githubusercontent.com/3756895/203625411-115a7b45-a44e-401e-a7a6-aa2ee2277cc7.mov


@marcellocamara I was trying to repro using your custom widget but I couldn't because the code of `Shimmer` class is not provided.
To help us best reproduce the issue, could you provide a working example with the most reduced code?

**Comment by marcellocamara** [comment]
Sure, @cyanglaz 

I will paste here the similar code, but without de shimmer:

```dart
import 'package:flutter/material.dart';
import 'package:google_mobile_ads/google_mobile_ads.dart';

class CustomAdBannerWidget extends StatefulWidget {
  final AdSize adSize;

  const CustomAdBannerWidget({
    super.key,
    this.adSize = AdSize.largeBanner,
  });

  @override
  CustomAdBannerWidgetState createState() => CustomAdBannerWidgetState();
}

class CustomAdBannerWidgetState extends State<CustomAdBannerWidget> {
  /// Visibility var
  bool _loading = true;
  bool _loaded = true;

  double get _width => widget.adSize.width.toDouble();

  double get _height => widget.adSize.height.toDouble();

  BannerAd? _bannerAd;

  @override
  void initState() {
    super.initState();
    _bannerAd = BannerAd(
      size: widget.adSize,
      request: const AdRequest(),
      adUnitId:
          'real-banner-id-to-be-used-on-release-with-authorized-test-device',
      listener: BannerAdListener(
        onAdLoaded: (Ad ad) {
          setState(() {
            _bannerAd = ad as BannerAd?;
            _loading = false;
          });
        },
        onAdFailedToLoad: (Ad ad, LoadAdError error) {
          ad.dispose();
          setState(() => _loaded = false);
        },
      ),
    )..load();
  }

  @override
  void dispose() {
    _bannerAd?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Visibility(
      visible: _loaded,
      child: Container(
        alignment: Alignment.bottomCenter,
        child: _loading || _bannerAd == null
            ? const Center(
                child: SizedBox(
                  width: 20,
                  height: 20,
                  child: CircularProgressIndicator.adaptive(
                    strokeWidth: 3,
                  ),
                ),
              )
            : SizedBox(
                width: _width,
                height: _height,
                child: AdWidget(ad: _bannerAd!),
              ),
      ),
    );
  }
}
```

Ps.: note that on yout video you're using test banner example
On my video you see that I'm using real banner with test mode (device configured to be in test mode on the AdMob Console - this shows real banner but in test, for your authorized device - I think the real banner make difference because on test banners - not real ones - I can't reproduce this bug too, as you)

**Comment by marcellocamara** [comment]
Sure, @cyanglaz 

I will paste here the similar code, but without the package:

```dart
import 'package:flutter/material.dart';
import 'package:google_mobile_ads/google_mobile_ads.dart';

class CustomAdBannerWidget extends StatefulWidget {
  final AdSize adSize;

  const CustomAdBannerWidget({
    super.key,
    this.adSize = AdSize.largeBanner,
  });

  @override
  CustomAdBannerWidgetState createState() => CustomAdBannerWidgetState();
}

class CustomAdBannerWidgetState extends State<CustomAdBannerWidget> {
  /// Visibility var
  bool _loading = true;
  bool _loaded = true;

  double get _width => widget.adSize.width.toDouble();

  double get _height => widget.adSize.height.toDouble();

  BannerAd? _bannerAd;

  @override
  void initState() {
    super.initState();
    _bannerAd = BannerAd(
      size: widget.adSize,
      request: const AdRequest(),
      adUnitId: 'real-banner-id-to-be-used-on-release-with-authorized-test-device',
      listener: BannerAdListener(
        onAdLoaded: (Ad ad) {
          setState(() {
            _bannerAd = ad as BannerAd?;
            _loading = false;
          });
        },
        onAdFailedToLoad: (Ad ad, LoadAdError error) {
          ad.dispose();
          setState(() => _loaded = false);
        },
      ),
    )..load();
  }

  @override
  void dispose() {
    _bannerAd?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Visibility(
      visible: _loaded,
      child: Container(
        alignment: Alignment.bottomCenter,
        child: _loading || _bannerAd == null
            ? const Center(
                child: SizedBox(
                  width: 20,
                  height: 20,
                  child: CircularProgressIndicator.adaptive(
                    strokeWidth: 3,
                  ),
                ),
              )
            : SizedBox(
                width: _width,
                height: _height,
                child: AdWidget(ad: _bannerAd!),
              ),
      ),
    );
  }
}
```

Ps.: Could you tell me the version you tested it? I think the new ones is fixed - In my case, I'm using 3.3.8 now. 
I didn't saw any lag on my new app (but now I'm implementing it different - just one banner fixed at the bottom - not on pages). I need to update this 2 examples to the new version an publish to see what happens

**Comment by cyanglaz** [comment]
> I didn't saw any lag on my new app 
>  I need to update this 2 examples to the new version an publish to see what happens

Did you mean the lag is fixed in 3.3.8? If that is the case, we can close this issue as 3.3.8 is now stable.

**Comment by marcellocamara** [comment]
Yes, it sound like it's fixed on the new versions.

Using `flutter 3.3.9` with `dart 2.18.5` and `google_mobile_ads 2.3.0`

I've updated the same app recorded here on both videos and can't reproduce it anymore. Yes, there is a time delay, but is much much better.

**Comment by OmerTrainer** [comment]
> Yes, it sound like it's fixed on the new versions.
> 
> Using `flutter 3.3.9` with `dart 2.18.5` and `google_mobile_ads 2.3.0`
> 
> I've updated the same app recorded here on both videos and can't reproduce it anymore. Yes, there is a time delay, but is much much better.

i am using newer versions than mentioned and i am still getting low frame rate in my app (only for ios)

**Comment by vaHeidi** [comment]
Using flutter 3.13.8 with dart 3.1.4 and google_mobile_ads 3.1.0 i am still getting low frame rate (only for ios)

**Comment by OmerTrainer** [comment]
same here

**Comment by bparrishMines** [comment]
@OmerTrainer @vaHeidi Please open a new issue if you are still seeing low performance. The original author has stated the performance for their specific issue has been fixed, so yours may be caused by something else or a regression.

**Comment by TiesPol** [comment]
Still facing this issue on Flutter 3.16.5, Dart 3.2.3 and google_mobile_ads 4.0.0. Especially on 120hz iPhone. Only having the scrolling jank when an ad is visible.
