### ISSUE TITLE
Undefined symbols for architecture i386

### ISSUE THREAD

**Issue by tonypottera24** [googleads/googleads-mobile-flutter#612]
## Plugin Version

`google_mobile_ads: ^1.3.0`

## Steps to Reproduce

```
flutter pub add google_mobile_ads
flutter run
```
**Expected results:** 

run the app

**Actual results:** 

<details>
  <summary>Logs</summary>

```
Launching lib/main.dart on iPhone 13 in debug mode...
lib/main.dart:1
Xcode build done.                                           20.4s
Failed to build iOS app
Error output from Xcode build:
↳
    2022-07-26 12:06:55.792 xcodebuild[47777:1067897] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
    2022-07-26 12:06:55.792 xcodebuild[47777:1067897] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
    ** BUILD FAILED **
Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/9h/lp36t37d5710z2qjdc7vf_d00000gn/T/flutter_tools.xEZMQe/flutter_ios_build_temp_dir4iDHQP/temporary_xcresult_bundle
    .../ios/Pods/DKPhotoGallery/DKPhotoGallery/DKPhotoGalleryContentVC.swift:39:52: warning: using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
    internal protocol DKPhotoGalleryContentDataSource: class {
                                                       ^~~~~
                                                       AnyObject
    .../ios/Pods/DKPhotoGallery/DKPhotoGallery/DKPhotoGalleryContentVC.swift:55:50: warning: using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
    internal protocol DKPhotoGalleryContentDelegate: class {
                                                     ^~~~~
                                                     AnyObject
    ld: warning: ignoring file /opt/local/lib/libz.dylib, building for iOS Simulator-i386 but attempting to link with file built for macOS-x86_64
    Undefined symbols for architecture i386:
      "_deflateInit2_", referenced from:
          +[NSData(GULGzip) gul_dataByGzippingData:error:] in GULNSData+zlib.o
      "_deflate", referenced from:
          +[NSData(GULGzip) gul_dataByGzippingData:error:] in GULNSData+zlib.o
      "_inflate", referenced from:
          +[NSData(GULGzip) gul_dataByInflatingGzippedData:error:] in GULNSData+zlib.o
      "_deflateEnd", referenced from:
          +[NSData(GULGzip) gul_dataByGzippingData:error:] in GULNSData+zlib.o
      "_inflateInit2_", referenced from:
          +[NSData(GULGzip) gul_dataByInflatingGzippedData:error:] in GULNSData+zlib.o
      "_inflateEnd", referenced from:
          +[NSData(GULGzip) gul_dataByInflatingGzippedData:error:] in GULNSData+zlib.o
    ld: symbol(s) not found for architecture i386
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order
    .../ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.5.99. (in target 'Toast' from project 'Pods')
    Result bundle written to path:
    	/var/folders/9h/lp36t37d5710z2qjdc7vf_d00000gn/T/flutter_tools.xEZMQe/flutter_ios_build_temp_dir4iDHQP/temporary_xcresult_bundle
Error (Xcode): Undefined symbol: _deflateInit2_

Error (Xcode): Undefined symbol: _deflate

Error (Xcode): Undefined symbol: _inflate

Error (Xcode): Undefined symbol: _deflateEnd

Error (Xcode): Undefined symbol: _inflateInit2_

Error (Xcode): Undefined symbol: _inflateEnd

Could not build the application for the simulator.
Error launching application on iPhone 13.
Exited
```

```
```

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-x64, locale en-TW)
    • Flutter version 3.0.5 at ...
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (12 天前), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at .../Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = .../Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (2 available)
    • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 12.5 21G72 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by tonypottera24** [comment]
After I build the project by Xcode, the error message changed to the following.
```
Launching lib/main.dart on iPhone 13 in debug mode...
Running pod install...                                              3.5s
Running Xcode build...                                                  
Xcode build done.                                            8.9s
Failed to build iOS app
Error output from Xcode build:
↳
    2022-07-26 13:01:47.316 xcodebuild[69954:1177221] Requested but did not find extension point with identifier
    Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in
    com.apple.dt.IDEWatchSupportCore
    2022-07-26 13:01:47.316 xcodebuild[69954:1177221] Requested but did not find extension point with identifier
    Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of
    plug-in com.apple.dt.IDEWatchSupportCore
    ** BUILD FAILED **


Xcode's output:
↳
    Writing result bundle at path:
        /var/folders/9h/lp36t37d5710z2qjdc7vf_d00000gn/T/flutter_tools.Z4TbTX/flutter_ios_build_temp_dirnUcHhy/temporary_xcresult_bundle

    Command CompileSwiftSources failed with a nonzero exit code
    Command CompileSwiftSources failed with a nonzero exit code
    Command CompileSwiftSources failed with a nonzero exit code
    ld: building for iOS Simulator, but linking in dylib built for macOS, file '/opt/local/lib/libz.dylib' for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order
    .../ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is
    set to 8.0, but the range of supported deployment target versions is 9.0 to 15.5.99. (in target 'Toast' from project 'Pods')

    Result bundle written to path:
        /var/folders/9h/lp36t37d5710z2qjdc7vf_d00000gn/T/flutter_tools.Z4TbTX/flutter_ios_build_temp_dirnUcHhy/temporary_xcresult_bundle


Uncategorized (Xcode): Command CompileSwiftSources failed with a nonzero exit code


Error (Xcode): Building for iOS Simulator, but linking in dylib built for macOS, file '/opt/local/lib/libz.dylib' for architecture x86_64


Could not build the application for the simulator.
Error launching application on iPhone 13.
```

**Comment by tonypottera24** [comment]
After I performs
```
flutter clean
rm ios/Pods
rm ios/Podfile.lock
fultter run
```
The error message goes back to the original one.

**Comment by huycozy** [comment]
Hi @tonypottera24 
Is this issue reproducible if you remove `google_mobile_ads` plugin?
Also, please check this [answer](https://github.com/flutter/flutter/issues/17749#issuecomment-615279343) that may help.

**Comment by tonypottera24** [comment]
Hi @huycozy 
thank you for helping me.
The error disappear after I comment out 
```
# google_mobile_ads: ^1.3.0
```
and run 
```
flutter run
```
directly without any `flutter clean`

**Comment by tonypottera24** [comment]
<img width="970" alt="Screen Shot 2022-07-26 at 2 32 37 PM" src="https://user-images.githubusercontent.com/3013707/180931230-f654d9a4-067b-46f8-bae4-e909ae6acc68.png">

**Comment by huycozy** [comment]
@tonypottera24 
Based on your log:
> .../ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is
    set to 8.0, but the range of supported deployment target versions is 9.0 to 15.5.99. (in target 'Toast' from project 'Pods')

Could you also try this workaround?
https://github.com/flutter/flutter/issues/17749#issuecomment-424461093

And also run `pod install` after `flutter clean` command:

```
flutter clean
flutter pub get
cd ios
pod install
flutter run
```

**Comment by tonypottera24** [comment]
I've this Podfile
```
# Uncomment this line to define a global platform for your project
platform :ios, '11.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```
Note that I uncomment `platform :ios, '11.0'` and changed 9.0 to 11.0
<img width="823" alt="Screen Shot 2022-07-26 at 3 23 37 PM" src="https://user-images.githubusercontent.com/3013707/180937871-309d1efc-7892-4d60-93e7-9c00f612fe1b.png">
<img width="874" alt="Screen Shot 2022-07-26 at 3 24 00 PM" src="https://user-images.githubusercontent.com/3013707/180937882-e3a6b688-53a0-4459-9973-9f15b0538a0a.png">

**Comment by tonypottera24** [comment]
I tried to change my Podfile as following (please check last parts).
```
# Uncomment this line to define a global platform for your project
platform :ios, '11.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        config.build_settings["ONLY_ACTIVE_ARCH"] = "YES"
    end
  end
end

```

However, `flutter run` still gives similar output.
```
Running "flutter pub get" in ...                            3.4s
Launching lib/main.dart on iPhone 13 in debug mode...
Running pod install...                                              3.4s
Running Xcode build...                                                  
Xcode build done.                                           10.1s
Failed to build iOS app
Error output from Xcode build:
↳
    2022-07-26 18:58:29.232 xcodebuild[71803:1737807] Requested but did not find extension point with identifier
    Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in
    com.apple.dt.IDEWatchSupportCore
    2022-07-26 18:58:29.232 xcodebuild[71803:1737807] Requested but did not find extension point with identifier
    Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of
    plug-in com.apple.dt.IDEWatchSupportCore
    ** BUILD FAILED **


Xcode's output:
↳
    Writing result bundle at path:
        /var/folders/9h/lp36t37d5710z2qjdc7vf_d00000gn/T/flutter_tools.fRljSV/flutter_ios_build_temp_dirHBt5tc/temporary_xcresult_bundle

    /.../.pub-cache/hosted/pub.dartlang.org/launch_review-3.0.1/ios/Classes/LaunchReviewPlugin.m:43:56: warning:
    'openURL:' is deprecated: first deprecated in iOS 10.0 [-Wdeprecated-declarations]
                        [[UIApplication sharedApplication] openURL:itunesURL];
                                                           ^~~~~~~
                                                           openURL:options:completionHandler:
    In module 'UIKit' imported from /.../ios/Pods/Target Support Files/launch_review/launch_review-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.5.sdk/System/Library/Frameworks/U
    IKit.framework/Headers/UIApplication.h:124:1: note: 'openURL:' has been explicitly marked deprecated here
    - (BOOL)openURL:(NSURL*)url API_DEPRECATED_WITH_REPLACEMENT("openURL:options:completionHandler:", ios(2.0, 10.0))
    NS_EXTENSION_UNAVAILABLE_IOS("");
    ^
    /.../.pub-cache/hosted/pub.dartlang.org/launch_review-3.0.1/ios/Classes/LaunchReviewPlugin.m:51:50: warning:
    'openURL:' is deprecated: first deprecated in iOS 10.0 [-Wdeprecated-declarations]
                  [[UIApplication sharedApplication] openURL:itunesURL];
                                                     ^~~~~~~
                                                     openURL:options:completionHandler:
    In module 'UIKit' imported from /.../ios/Pods/Target Support Files/launch_review/launch_review-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.5.sdk/System/Library/Frameworks/U
    IKit.framework/Headers/UIApplication.h:124:1: note: 'openURL:' has been explicitly marked deprecated here
    - (BOOL)openURL:(NSURL*)url API_DEPRECATED_WITH_REPLACEMENT("openURL:options:completionHandler:", ios(2.0, 10.0))
    NS_EXTENSION_UNAVAILABLE_IOS("");
    ^
    /.../.pub-cache/hosted/pub.dartlang.org/launch_review-3.0.1/ios/Classes/LaunchReviewPlugin.m:73:37: warning:
    'sendSynchronousRequest:returningResponse:error:' is deprecated: first deprecated in iOS 9.0 - Use [NSURLSession
    dataTaskWithRequest:completionHandler:] (see NSURLSession.h [-Wdeprecated-declarations]
        NSData *data = [NSURLConnection sendSynchronousRequest:request returningResponse:&response error:&error];
                                        ^
    In module 'UIKit' imported from /.../ios/Pods/Target Support Files/launch_review/launch_review-prefix.pch:2:
    In module 'Foundation' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.5.sdk/System/Library/Frameworks/U
    IKit.framework/Headers/UIKit.h:8:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.5.sdk/System/Library/Frameworks/F
    oundation.framework/Headers/NSURLConnection.h:405:1: note: 'sendSynchronousRequest:returningResponse:error:' has been explicitly marked
    deprecated here
    + (nullable NSData *)sendSynchronousRequest:(NSURLRequest *)request returningResponse:(NSURLResponse * _Nullable * _Nullable)response
    error:(NSError **)error API_DEPRECATED("Use [NSURLSession dataTaskWithRequest:completionHandler:] (see NSURLSession.h", macos(10.3,10.11),
    ios(2.0,9.0), tvos(9.0,9.0)) API_UNAVAILABLE(watchos);
    ^
    3 warnings generated.
    ld: building for iOS Simulator, but linking in dylib built for macOS, file '/opt/local/lib/libz.dylib' for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    Command CompileSwiftSources failed with a nonzero exit code
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order

    Result bundle written to path:
        /var/folders/9h/lp36t37d5710z2qjdc7vf_d00000gn/T/flutter_tools.fRljSV/flutter_ios_build_temp_dirHBt5tc/temporary_xcresult_bundle


Error (Xcode): Building for iOS Simulator, but linking in dylib built for macOS, file '/opt/local/lib/libz.dylib' for architecture x86_64


Uncategorized (Xcode): Command CompileSwiftSources failed with a nonzero exit code


Could not build the application for the simulator.
Error launching application on iPhone 13.
```

**Comment by huycozy** [comment]
@tonypottera24 

> I don't know why the IPHONEOS_DEPLOYMENT_TARGET warning still exists even though I've already set it to 11.0

> /.../ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is
    set to 8.0, but the range of supported deployment target versions is 9.0 to 15.5.99. (in target 'Toast' from project 'Pods')

In this case, let's set deployment target for Toast Pod, for eg (camera Pod in my example):

<img width="400" src=""> | <img width="600" src="https://user-images.githubusercontent.com/104349824/180994613-fb266d37-dd51-48c8-8bfc-01cdff062ddf.png">

**Comment by tonypottera24** [comment]
@huycozy thank you for helping me.
After adding
```
config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
```
in the Podfile, the error message disappeared.
I'm not sure if this is a good practice...

**Comment by huycozy** [comment]
@tonypottera24 Nice. Can you confirm the issue has been solved? 
There are many issues similar to this because it depends on the computer architecture, package dependencies of each project, etc. Therefore, please try to read the errors/logs carefully and also find solutions on Google, Stackoverflow, etc.

**Comment by tonypottera24** [comment]
I'm sorry that the problem still exists.
my computer is MacBook pro 2019 (intel CPU).
Therefore, my issue is different from those who use M1 or M2 CPUs.
The main error message is
```
ld: building for iOS Simulator, but linking in dylib built for macOS, file '/opt/local/lib/libz.dylib' for architecture x86_64
```
The path `/opt/local/` is used by `macport`. I cannot remove libz to solve this issue since there are many packages depends on libz.
I noticed that people who use M1 CPU tend to have `ld: ... for architecture arm64`, but in my case it is `ld: ... for architecture x86_64`
I tried to exclude `x86_64`, but this caused another error.

**Comment by tonypottera24** [comment]
```
Xcode's output:
↳
    Writing result bundle at path:
        /var/folders/9h/lp36t37d5710z2qjdc7vf_d00000gn/T/flutter_tools.ionpDT/flutter_ios_build_temp_dirLTy4nY/temporary_xcresult_bundle

    Command CompileSwiftSources failed with a nonzero exit code
    Command CompileSwiftSources failed with a nonzero exit code
    ld: warning: ignoring file /opt/local/lib/libz.dylib, building for iOS Simulator-arm64 but attempting to link with file built for macOS-x86_64
    Undefined symbols for architecture arm64:
      "_deflateInit2_", referenced from:
          +[NSData(GULGzip) gul_dataByGzippingData:error:] in GULNSData+zlib.o
      "_deflate", referenced from:
          +[NSData(GULGzip) gul_dataByGzippingData:error:] in GULNSData+zlib.o
      "_inflate", referenced from:
          +[NSData(GULGzip) gul_dataByInflatingGzippedData:error:] in GULNSData+zlib.o
      "_deflateEnd", referenced from:
          +[NSData(GULGzip) gul_dataByGzippingData:error:] in GULNSData+zlib.o
      "_inflateInit2_", referenced from:
          +[NSData(GULGzip) gul_dataByInflatingGzippedData:error:] in GULNSData+zlib.o
      "_inflateEnd", referenced from:
          +[NSData(GULGzip) gul_dataByInflatingGzippedData:error:] in GULNSData+zlib.o
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order

    Result bundle written to path:
        /var/folders/9h/lp36t37d5710z2qjdc7vf_d00000gn/T/flutter_tools.ionpDT/flutter_ios_build_temp_dirLTy4nY/temporary_xcresult_bundle


Uncategorized (Xcode): Command CompileSwiftSources failed with a nonzero exit code


Error (Xcode): Undefined symbol: _deflateInit2_


Error (Xcode): Undefined symbol: _deflate


Error (Xcode): Undefined symbol: _inflate


Error (Xcode): Undefined symbol: _deflateEnd


Error (Xcode): Undefined symbol: _inflateInit2_


Error (Xcode): Undefined symbol: _inflateEnd


Could not build the application for the simulator.
Error launching application on iPhone 13.
```
Based on current error message, I'm inspecting why libz is not linked correctly.
I tried to add `libz.tbd` in `Link Binary With Libraries`, but it still gives the same error message.

**Comment by tonypottera24** [comment]
I've the same issue as this one
https://stackoverflow.com/questions/24550889/building-for-ios-simulator-but-linking-against-dylib-built-for-macosx-file-op

**Comment by tonypottera24** [comment]
This issue is resolved by changing following line in `.bashrc`
from
```
export LIBRARY_PATH=/opt/local/lib
```
to
```
export LIBRARY_PATH=/usr/lib:/opt/local/lib
```
Note that `/usr/lib` should be placed before `/opt/local/lib`.
@huycozy Can I change this setting in Xcode instead of changing the global setting it in `.bashrc`?

**Comment by huycozy** [comment]
Hi @tonypottera24 
Based on your last update, the issue occurred on your local machine where MacPorts is installed. Please see https://flutter.dev/community for resources and ask questions like this.

You may also get some help if you post it on Stack Overflow and if you need help with your code, please see https://www.reddit.com/r/flutterhelp.

Closing, as this isn't an issue with Ads itself. Thank you!
